spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: aggregation
      password: aggregation
      database: aggregation
      auto-index-creation: true
#      authentication-database: admin